### ISSUE TITLE
Crash in `CalcDistance()` function

### ISSUE THREAD

**Issue by rfomin** [fabiangreffrath/woof#1142]
Each sector has `degenmobj_t` for sound purposes, instead of `mobj_t`.  `degenmobj_t` doesn't have `mobjinfo_t` pointer, so the program crashes at this line:
https://github.com/fabiangreffrath/woof/blob/1d644070d8b7464792536f41ddd893df32d4f7bb/src/i_3dsound.c#L174

How to reproduce: choose openal sound backend, start the MAP01 of aaliens.wad, open first door.

**Comment by rfomin** [comment]
Possible fix:
```diff
diff --git a/src/p_setup.c b/src/p_setup.c
index 0ce86b0..ee37ba2 100644
--- a/src/p_setup.c
+++ b/src/p_setup.c
@@ -1262,6 +1262,7 @@ int P_GroupLines (void)
 			    sector->blockbox[BOXLEFT])/2;
       sector->soundorg.y = (sector->blockbox[BOXTOP] + 
 			    sector->blockbox[BOXBOTTOM])/2;
+      sector->soundorg.info = NULL;
 
       // adjust bounding box to map blocks
       block = (sector->blockbox[BOXTOP]-bmaporgy+MAXRADIUS)>>MAPBLOCKSHIFT;
diff --git a/src/r_defs.h b/src/r_defs.h
index 1ebe2e1..f333f5b 100644
--- a/src/r_defs.h
+++ b/src/r_defs.h
@@ -69,6 +69,7 @@ typedef struct
 {
   thinker_t thinker;  // not used for anything
   fixed_t x, y, z;
+  mobjinfo_t *info;
 } degenmobj_t;
 
 //
```

**Comment by fabiangreffrath** [comment]
Or we could just let `thinker` point to `NULL`?

**Comment by fabiangreffrath** [comment]
Or we could introduce a dummy `P_DegenMobjThinker()` action pointer which did nothing, and have each `degenmobj->thinker` point there.

**Comment by ceski-1** [comment]
I remember `degenmoj_t` bothering me and forgot to discuss it earlier. If I'm reading it correctly, the dummy `thinker` field in `degenmoj_t` is only there to preserve alignment when a "soundorg" is cast to `mobj_t` when playing a sound. Example:

https://github.com/fabiangreffrath/woof/blob/1d644070d8b7464792536f41ddd893df32d4f7bb/src/p_ceilng.c#L78

So would adding `mobjinfo_t *info;` to `degenmoj_t` cause issues since the other fields aren't there as padding?

Related to this, `S_UnlinkSound()` does something similar:

https://github.com/fabiangreffrath/woof/blob/1d644070d8b7464792536f41ddd893df32d4f7bb/src/s_sound.c#L335-L339

Maybe the `sobjs` array should use the full `mobjinfo_t` in order to preserve `info->actualheight` otherwise the 3D sound module will not be able to determine vertical position:

https://github.com/fabiangreffrath/woof/blob/1d644070d8b7464792536f41ddd893df32d4f7bb/src/i_3dsound.c#L173-L190
