### ISSUE TITLE
Don't Disable Cheats in Strict mode

### ISSUE THREAD

**Issue by OpenRift412** [fabiangreffrath/woof#1226]
Not entirely sure why this is the case, but I think having cheats still work with strict mode set to on would be better since the cheats are a legacy functionality.

**Comment by MrAlaux** [comment]
Correct me if I'm wrong, but I believe Strict Mode disables cheats because its intention is to disable features that'd be considered cheating as per DSDArchive's (i.e. Doom speedrunning) rules. Yes, many cheats are already disabled while recording demos, but a handful of them (like `IDDT`) can still be used.

**Comment by fabiangreffrath** [comment]
Yes, indeed strict mode does not have to do with "legacy functionality" but is merely there to prevent people from accidently invalidating their demo recording attempts by using "forbidden features". It is there to make sure that game play adheres to DSDA rules, and this of course forbids cheat codes.

**Comment by fabiangreffrath** [comment]
Should we rename "strict mode" to something less ambigious? "speed running rules compliance" comes to mind, but that's a bit long, obviously. Any thoughts @rfomin @kraflab ?

**Comment by rfomin** [comment]
Maybe we should enable cheat codes in strict mode? They will be disabled during the demo recording anyway.

**Comment by fabiangreffrath** [comment]
Hm, haven't seen it that way. 🤔

**Comment by rfomin** [comment]
> As easy as this?

Yes, I think so.
