### ISSUE TITLE
fix parsing lump names in u_scanner.c

### ISSUE THREAD

**Issue by fabiangreffrath** [fabiangreffrath/woof#1288]
By now, lump names are parsed as `TK_Identifier` type tokens, which means the range of chars they may consist of is restricted to letters, numbers and underscores. The alternative is to parse them as `TK_StringConst` type tokens, but these require quoting. We either need a new token category or a means to explicitly relax the char restriction for `TK_Identifier` type tokens as needed.

**Comment by rfomin** [comment]
I propose this solution: https://github.com/fabiangreffrath/woof/pull/1289 More testing is required.

**Comment by fabiangreffrath** [comment]
Thanks for this! Not sure if reading a string isn't a bit too general. We only need this change in one specific place, and there it is about reading a lump name, so we could even restrict its length to be 8 chars or less.

**Comment by rfomin** [comment]
> We only need this change in one specific place

But if we change U_GetToken so that it accepts lump names (any data), then u_scanner loses its strictness and becomes essentially the sc_man scanner from Hexen.
We can read lump names correctly as it is, they just have to be enclosed in `"`. I think this is a good limitation. U_GetString is a hack to get the old MUSINFO working.

**Comment by rfomin** [comment]
https://github.com/fabiangreffrath/woof/commit/286e0c375091d0ebfb08001c9c7321e56bab3ea9
