### ISSUE TITLE
-statdump is not working for E*M8

### ISSUE THREAD

**Issue by Dezaimasu** [fabiangreffrath/woof#1313]
After finishing E*M8 level, watching the text screen and quitting the game the txt file specified with -statdump option is empty. When quitting after any other level the stats are properly saved to stats file, but after E1M8 or E2M8 the file is empty, 0 bytes.
I'm using Woof-12.0.0, launching the game with:
woof.exe -iwad "DOOM.WAD" -warp 1 8 -skill 4 -statdump stats.txt

**Comment by fabiangreffrath** [comment]
As already stated, this is the original statdump behavior. To provide some rationale: statdump output has been added to Chocolate Doom to perform a compatiblity test in which a number of demos was run and the statdump output compared to that of Vanilla Doom. I have adapted this feature to Woof rather early to perform the same tests here. However, statdump never reported any statistics for ExM8 and so we had to keep it the same in Woof, because if we reported these statistics whereas Vanilla didn't, then this would be a deviation and thus a bug.

The `-levelstat` feature is considered as the modern successor of `-statdump`.
