### ISSUE TITLE
Some savegame slots are omitted

### ISSUE THREAD

**Issue by MrAlaux** [fabiangreffrath/woof#1318]
_Tested in the [latest master artifact (x64)](https://github.com/fabiangreffrath/woof/actions/runs/7157452216)._

An example:

- The first slot in Page 1 corresponds to `woofsav0.dsg`;
- The last slot in Page 1 corresponds to `woofsav7.dsg`;
- The first slot in Page 2 corresponds to `woofsav10.dsg`.

As you may notice, `woofsav8.dsg` and `woofsav9.dsg` are omitted. It's as if each Page had 10 saves, but only displayed 8 of them.

I'm pretty sure that changing this, though, would mess with existing saves (i.e. saves in Pages after the first one would be shifted to later Pages).

**Comment by fabiangreffrath** [comment]
Yes, this is because for some reason I was assuming 10 savegames per page when I first implemented this feature. Counting is hard, you know. However, it is too late to fix it now, because it would completely mess up peoples' savegame arrangements and we would need to add two more pages to still show the last available slot. 

If you read the file names as `woofsav<page-index><slot-index>` it suddenly starts to make a lot more sense. 😉
