### ISSUE TITLE
Executable version has an extra ".0"

### ISSUE THREAD

**Issue by MrAlaux** [fabiangreffrath/woof#1319]
_Verified in the [latest master artifact (x64)](https://github.com/fabiangreffrath/woof/actions/runs/7157452216)._

See (mind the language):
![imagen](https://github.com/fabiangreffrath/woof/assets/73968015/47bb8420-85d0-40ef-bf60-61c72896034e)

Could it be because of the `,0` in here?
https://github.com/fabiangreffrath/woof/blob/3efb4a8b1648bd2d249244ba4fa3fc8a373dd2c6/CMakeLists.txt#L45-L45

Regardless of whichever part of the code is responsible, is it intentional? I see the comment right next to that line, but I'm still unsure. Is it some future-proofing of sorts?

**Comment by fabiangreffrath** [comment]
Yes, this is because for some reason Windows actually expects version information to be given as four components in a RC file. 

https://learn.microsoft.com/en-us/windows/win32/menurc/versioninfo-resource

I remember it will even fail with a compilation error if given only three components, at least with mingw.
