### ISSUE TITLE
horizontal mouselook seems to still have acceleration after setting it off.

### ISSUE THREAD

**Issue by ShroomiePerson** [fabiangreffrath/woof#1387]
with mouse acceleration set to 1, or 0 in the config file, there is still mouse acceleration. i have also tried messing with mouse threshold but it doesn't seem to fix anything.

**Comment by ceski-1** [comment]
There's no mouse acceleration if you disable it. Are you maybe noticing latency? If you are on Windows you can try one of the latest artifacts. Mouse smoothing is removed and interpolation is disabled by default.

**Comment by ShroomiePerson** [comment]
i installed via macos homebrew, so unless use have instructions and i can build from the latest artifact, i think i'm out of luck. anyways, i doubt there's any proper latency, as when i start moving my mouse, there is none; when i stop, the world keeps spinning for a minuscule yet still disorienting amount of time.

**Comment by ceski-1** [comment]
> i doubt there's any proper latency, as when i start moving my mouse, there is none; when i stop, the world keeps spinning for a minuscule yet still disorienting amount of time.

That's likely due to mouse smoothing and interpolation. As a troubleshooting step, you can temporarily set "uncapped frame rate" to "no" which will disable interpolation and see if it still happens. Then set it back to "yes" afterwards.

But since this is a open-ended issue, there are many possible causes.
1. Performance issue? Type `showfps` and see if the framerate is stable.
2. Video options issue? Experiment "exclusive fullcreen" and "vertical sync".
3. Interpolation issue? Build from source to see if the recent mouse updates help: 

```
brew uninstall woof-doom
brew install woof-doom --build-from-source
```
or
```
brew install git ninja cmake sdl2 sdl2_net openal-soft libsndfile fluid-synth libxmp
git clone https://github.com/fabiangreffrath/woof.git
cd woof
cmake -B build -G Ninja
cmake --build build
```
The executable will be in `/woof/build/src`.

**Comment by ShroomiePerson** [comment]
huh, brew installs Woof 12.0.2 (no matter whether i use `--build-from-source` or not,) while building from the git repo gets be 12.0.0, and using that version solves the problem.

**Comment by fabiangreffrath** [comment]
If you build from the repo you get the yet-unversioned development snapshot that still carries the 12.0 version number.

**Comment by ShroomiePerson** [comment]
aah, alright, thank you! ill use this for now.

**Comment by mikeday0** [comment]
A clarification. `brew install --build-from-source` will download a source tarball of the latest released version and build it locally. `brew install --HEAD` will check out the git repository and build from the latest commit on the master branch.
