### ISSUE TITLE
Blocky fuzz issues

### ISSUE THREAD

**Issue by ceski-1** [fabiangreffrath/woof#1458]
Moving this topic to a dedicated issue.

ceski:

> As an aside, the last time I looked at blocky fuzz with the new resolution code it had some significant artifacts (see the fuzz test wad I made). Maybe it should be tweaked a bit before the next release.

> Fuzz hasn't looked right at some point after this commit: #1217

> Try a few different resolutions while looking at the test pattern that replaces the pistol. Then take a look at the fist and how it looks when it's returning to an idle state after coming to a stop (it shrinks in a strange manner). Even without the fuzz effect, player sprites look a little odd when returning to an idle state (move around a bit and then let the weapon sprite return to center).

rfomin:

> I think it's the aftermath of #1377 Perhaps we should revert it.

> I've tested blocky fuzz more and the test pattern that replaces the pistol doesn't look right at many resolutions, e.g. at 300%

**Comment by rfomin** [comment]
There are problems noticeable in fuzztest.wad in some resolutions when the player doesn't move. But I think it's a minor issue that shouldn't delay the release.

**Comment by ceski-1** [comment]
Agreed. I didn't want it buried in the changelog PR.

**Comment by fabiangreffrath** [comment]
I think the underlying issue is that we omit the fractional part of non-integer resulutions and only increase steps by the integer part here:

https://github.com/fabiangreffrath/woof/blob/fd24d9cb75e4b75d9d45eb68197c36974fa6666d/src/r_draw.c#L542-L543

For resolutions like 250% this means we only increase in steps of 2 px horizontally and vertically, whereas we would have to increase by alternating steps of 2 px and 3 px (since we can't go by 2.5 px in one step). This makes the whole fuzzy area look finer grained than required.
