### ISSUE TITLE
In-Game Compatibility Preset Toggle?

### ISSUE THREAD

**Issue by OpenRift412** [fabiangreffrath/woof#160]
Any possibility of having a compatibility toggle in the settings menu? I know it can be done from the command line, but it would be nice to see this toggle in the general settings menu, similar to how PrBoom-plus does it.

**Comment by rfomin** [comment]
Are you talking about complevel menu switching? GZDoom does this, not PrBoom+. Due to changes in the friction code, you need to restart the map, save can also break. I think complevels is an advanced feature, we will have better defaults in the next release, so hopefully most users don't need to change it.

**Comment by fabiangreffrath** [comment]
PrBoom+ has a *default* complevel switch in the menu which decides which complevel to use if not playing back a demo or explicitly requested otherwise. I think we can add this, too.
