### ISSUE TITLE
[proposal] uncoupled_input

### ISSUE THREAD

**Issue by gendlin** [fabiangreffrath/woof#1707]
Following up from a [doomworld discussion](https://www.doomworld.com/forum/post/2803657) with @ceski-1 related to **raw_input** and the as-yet-unreleased **fake_longtics** PR #1691. My understanding is that **raw_input** currently controls a mixture of interpolation and coupling to the game tic, depending on the game mode:

| | interpolation | coupling |
|--------|--------|--------|
| raw_input=0 | ✅ | ✅ |
| raw_input=1 | 🔳 | 🔳 |
| [shorttics] raw_input=1 | 🔳 | ✅ | 
| [shorttics] raw_input=1, fake_longtics=1 | 🔳 | 🔳 |

My thought is that it might be better to just split these concepts apart, and have **raw_input** control interpolation alone, and rename **fake_longtics** to something like **uncoupled_input** and allow it to control tic coupling across the board (to match current behavior, both would be defaulted on). This has the following advantages:

- Being more explicit about what is actually going on
- Unified behavior between shorttics / longtics
- **uncoupled_input** config option has no hidden dependency on **raw_input** setting (not the case with **fake_longtics**)
- Allows players access to a potentially interesting new mode: (interpolation on, coupling off)

I wanted to air this as a possibility before **fake_longtics** goes out the door as a released config option and can no longer be changed. Thoughts?

**Comment by ceski-1** [comment]
> My understanding is that raw_input currently controls a mixture of interpolation and coupling to the game tic, depending on the game mode

Here is the current behavior:

`raw_input 0`
- Gamepad/mouse input for turning/looking is read once per ticcmd update.
- When the frame rate is uncapped, the input is interpolated. Otherwise the input is not interpolated.
- Mouse acceleration and threshold behave like Chocolate Doom ([details](https://www.doomworld.com/forum/post/2780155)).
- Shorttics is always "coarse".

`raw_input 1` (default)
- Gamepad/mouse input for turning/looking is read once per frame, independent of ticcmd updates.
- The input is never interpolated, hence "raw".
- Mouse acceleration acts as an overall sensitivity multiplier only. Threshold is ignored.
- If using `fake_longtics 0`, then shorttics is "coarse".
- If using `fake_longtics 1`, then shorttics is "smooth" (default).

> My thought is that it might be better to just split these concepts apart

I can't think of a way of making `fake_longtics` work without `raw_input`. The defaults should make most people happy and only power users should be changing them.

> Allows players access to a potentially interesting new mode: (interpolation on, coupling off)

I don't see the benefit of such a combination. It seems like the worst of both worlds.

**Comment by ceski-1** [comment]
@gendlin Can you try the build [here](https://github.com/fabiangreffrath/woof/actions/runs/9245421098) and let me know if that addresses your request? In that build, `fake_longtics` and `raw_input` are separate settings.
