### ISSUE TITLE
suggestion: change load order for the "autoload" feature

### ISSUE THREAD

**Issue by rfomin** [fabiangreffrath/woof#171]
I think most users will try the "autoload" feature with wide assets, doom minor sprite fix project, hires sounds, etc. So we have to load this before PWADs from the `-file` parameter or drag-n-drop.

**Comment by fabiangreffrath** [comment]
I agree. However, I think we will need a more sophisticated DEHACKED patch loading algorithm to keep them in a certain order.

**Comment by rfomin** [comment]
> more sophisticated DEHACKED patch loading algorithm

Why? I tried to rearrange the functions, at first glance it works.

**Comment by fabiangreffrath** [comment]
So, you moved the `D_ProcessWadPreincludes()` line right before the `if ((p = M_CheckParm ("-file")))` block? Looks abcolutely reasonable. BUT, there is one change to consider: DEHACKED lumps are parsed from last-added to first-added, so by changing the order in which PWADs are added we also change the order in which DEHACKED lumps are processed. That's why I said we need a more sophisticated algorithm to sort them, at least in the longer term.

**Comment by rfomin** [comment]
> DEHACKED lumps are parsed from last-added to first-added

Is this true and for the `-file` parameter? So currently user can't affect the load order of DEHACKED lumps?
For autoload I have this output:
```
W_Init: Init WADfiles.
 adding .\doom2.wad
 adding .\autoload\doom-all\SMOOTHED.wad
 adding .\autoload\doom-all\vsmooth.wad
 adding .\autoload\.\doom2.wad\wide_d2.wad
 adding d:\OLD\DOOM\WAD\rush.wad

Loading DEH file SMOOTHED.wad
Loading DEH file vsmooth.wad
Loading DEH file rush.wad
```

**Comment by fabiangreffrath** [comment]
Ah, not exactly, apparently. First, all DEH files given on the command line are processed, then all DEHACKED lumps embedded in WADs and then all DEH files in the autoload directory. This global ordering would even remain if we moved the autoload WADs before the command line WADs.

**Comment by fabiangreffrath** [comment]
Isn't this fixed by https://github.com/fabiangreffrath/woof/commit/411874e3705b4b13c2775d0fc23c9245763d1f5f now?

**Comment by rfomin** [comment]
Yes, I think it is.
