### ISSUE TITLE
Automap thing triangle doesn't represent thing's hitbox exactly

### ISSUE THREAD

**Issue by MrAlaux** [fabiangreffrath/woof#1794]
_Tested in the [latest master artifact (Win-64)](https://github.com/fabiangreffrath/woof/actions/runs/9939286691)._

Simply put, I would expect the triangle's corners to be on the edges of the thing's hitbox (assuming that the thing is facing a cardinal direction), but that's only the case with the "tip" corner.

Just yesterday, I implemented a feature in Nugget that allows to visualize hitboxes accurately, which lets us see the discrepancy:
![imagen](https://github.com/user-attachments/assets/636dc9a5-77be-4cee-8c14-fa414f6a636b)

The grey lines represent the hitboxes accurately, and the thing on the right is facing straight west. As you may see, the player arrow also doesn't represent the hitbox with much accuracy.

These "inaccuracies" could very well be intentional, but I wanted to mention them in case you'd like to make changes.

**Comment by fabiangreffrath** [comment]
Well, in both Vanilla Doom [1] and even the original MBF [2], all things on the Automap (except for the players, that is) are represented by triangles of the exact same size (scaled by `16<<FRACBITS`, fwiw). So, a bullet puff and a Spider Mastermind would just appear the same. I just changed this to take the actual thing radius into account in Crispy Doom some 10 years ago [3].

So, I wouldn't say these inaccuracies were "intentional". It's rather that nobody ever gave a damn how accurately the triangles represented the things actual hitboxes before. :wink:

[1] https://github.com/id-Software/DOOM/blob/a77dfb96cb91780ca334d0d4cfd86957558007e0/linuxdoom-1.10/am_map.c#L1299
[2] https://github.com/Doom-Utils/historic-ports/blob/12f0105340a2aaae66a0a3efac6bd8b9af5f960c/am_map.c#L1677
[3] https://github.com/fabiangreffrath/crispy-doom/commit/b9206b2e79fbf9b38b8abed3e2486b43cbeb04e8

**Comment by fabiangreffrath** [comment]
I take this as an observation, but not as anything that we need to fix.
