### ISSUE TITLE
midi: add GUS emulation device

### ISSUE THREAD

**Issue by elf-alchemist** [fabiangreffrath/woof#1937]
One of the few features I miss in Woof is proper GUS patch support, be it EAWPATS or GUSPPL1.61 it is undoubtedly my personal second favorite favorite sound for Doom, losing only, of course to the  SC55. With all of Crispy, GZDoom and KEX supporting it, it's a bit of a shame not to have it on Woof.

![image](https://github.com/user-attachments/assets/2679327e-6199-468e-b503-cb3a0ee99b77)

**Comment by rfomin** [comment]
I like Timidity, but maybe we'll get a real GUS emulation soon: https://twitter.com/nukeykt/status/1804172474814185543

**Comment by NightFright2k19** [comment]
Nukeykt is a godsent regarding emulation of MIDI devices. I wouldn't be surprised if we soon even get YXG50 emulation, then we have pretty much all bases covered.

**Comment by ceski-1** [comment]
@elf-alchemist The GUS emulation you're used to is just pairing a patch set like eawpats with Timidity. I don't think it makes sense to support Timidity in a modern source port (it appears that other ports only added it at a time when better alternatives didn't exist yet). However, have you tried the [eawpats soundfont](https://musical-artifacts.com/artifacts/3101) with either FluidSynth or VirtualMIDISynth? It sounds the same as eawpats + Timidity ([comparison video by the author](https://www.youtube.com/watch?v=kv4lwVWkYlo)). There are also at least two other GUS soundfonts, like [this one](https://musical-artifacts.com/artifacts/3234) that is supposedly more accurate to the original hardware.

**Comment by ceski-1** [comment]
Another option with Linux (not sure about Windows) is to run Timidity in the background and select it from Woof's menu. In this case, it behaves as a native MIDI device.

This actually brings up another point: Since Woof provides cross-platform native MIDI output, it opens up [a wide range of MIDI options](https://www.doomworld.com/forum/post/2794580). If a "Nuked-GUS" is ever realized in the future, then it would work using native MIDI as well.
