### ISSUE TITLE
port build system to CMake?

### ISSUE THREAD

**Issue by fabiangreffrath** [fabiangreffrath/woof#21]

**Comment by AlexMax** [comment]
Did someone mention CMake? 😀

In all seriousness, what are you looking for in terms of CMake?  Are you simply looking for a way to build the binary on Windows, to allow Windows developers to contribute?  Or are you looking to completely replace the autotools build system with CMake?

**Comment by fabiangreffrath** [comment]
Hi @AlexMax, I am glad you found your way here. :grin: 

The main reason why I want a CMake build script is because I want people to be able to build this project with Visual Studio. I know that installing MSYS2 and working with a bash shell is a high entrance burden for contributors, even for experienced programmers who are otherwise used to the Windows workflow.

Honestly, I don't like CMake myself. I find it just as cryptic and hard to understand as Automake, but at least I am more familiar with the latter. However, I know that the future doesn't belong to Automake and maybe a little side project like this one is a good playground to try out other solutions. So, yes, if we can develope a CMake build script that does exactly what the Automake solution does today, I would be willing to do the switch. The prboom-plus fork at https://github.com/coelckers/prboom-plus already did that.

**Comment by AlexMax** [comment]
I cooked something up this evening for ya, based on my prior work on Chocolate Doom and DietBoom.  I put a few little extra twists on it, and came up with #48.  Take a look and let me know how you like it.

**Comment by chungy** [comment]
My two cents: I also find CMake fairly cryptic and hard to understand. A bit moreso than I find autotools (though the difference isn't massive, I'd grant), at least on the developer side. I think the end-user experience is significantly worse¹, especially the propensity I've experienced for CMake scripts to go out of date with their dependence on a system-installed cmake and just refuse to work. Autotools-generated files (eg, ./configure) at least work after many decades of not being touched, even if the \*.in\/\*.am\/\*.ac files no longer work with the current autoconf/automake. The future might not belong to Autotools, but I don't believe it really belongs to CMake either; it can be just as bad or even worse in some aspects.

I would prefer not deleting the Autotools files nor switching the primary focus from them, but I also understand a desire to be simple and stick to just one build system instead of maintaining two. I wouldn't have any large issues with a total upending switch, but I have a preference and it isn't cmake.

¹ I cannot for the life of me ever, _ever_ remember the cmake-equivalent of `./configure --help` -- I think it exists but `cmake --help` itself is rather unhelpful. This facet alone is how I qualify it as significantly worse.

**Comment by AlexMax** [comment]
Believe you me, I am not the biggest fan of CMake.  I have done some incredibly gnarly things with it in the past, and even some of the things I've done for this build I hated writing - see some of the things I had to do surrounding `install` and `WoofInstall.cmake.in` for a glimpse.

But the thing is, the choice is very simple to me.  Automake does not support Windows unless you force people to install a POSIX-style environment to run it in.  So unless the project is a *NIX tool, that fact, on it's face, disqualifies it from being the sole build system for a project in my book.

And once we're past that disqualifier, CMake really does seem like the last man standing.  xmake looks like a promising up-and-comer, as does meson, but right now CMake looks like it has the majority of developer mind-share.  I remember seeing [this survey](https://www.jetbrains.com/lp/devecosystem-2019/cpp/) which reported that CMake is the build system used by 43% of respondents.  I found [another one](https://www.bfilipek.com/2019/12/cpp-status-2019.html) where CMake was used by 66% of respondents.

**Comment by chungy** [comment]
> EDIT: Forgot to mention that multiple build systems seems unwise if at all possible. If a build system doesn't have an active developer doing development with it, then it will languish from lack of - or worse, untested - updates.

It is possible, see the Chocolate Doom project. See also the Chocolate Doom project for how often the CMake files go out of date and proving your point about the downsides :)

**Comment by AlexMax** [comment]
> See also the Chocolate Doom project for how often the CMake files go out of date and proving your point about the downsides.

By "out of date" I mean people forgetting to add files to the alternative build, or introducing new defines or compiler settings that don't get reflected to the alternative build system.  The sort of thing that would happen no matter if the alternative build system was CMake, meson, automake, or a Visual Studio project.

**Comment by AlexMax** [comment]
To get back on track, and to make my position clear, I am not wed to CMake.  If @fabiangreffrath would like me to investigate a less divisive alternative, I am on board with that, despite the work I put into the current CMake build system.

The outcome I would like to avoid at all costs is having two parallel build systems.

**Comment by fabiangreffrath** [comment]
Thanks for the discussion, guys. @AlexMax I won't ask you to explore a new build system, I am fine with CMake as long as it provides the same features and flexibility as the current Automake implementation and provides the extra bonus of being able to create Visual Studio project files.

There won't be two concurrent build systems (for a longer time). I guess I'll bite the bullet and switch to CMake once I have ironed out the other stability and usability issues in this project.
