### ISSUE TITLE
feature suggestion: Implement Crispy Doom style brightmaps

### ISSUE THREAD

**Issue by AtifArshad1995** [fabiangreffrath/woof#404]
Hi Fabian. I really like what you are doing with Woof. Keep up the great work.

Now, since Woof already has some of the Crispy Doom type features like colored blood, I was wondering if you can implement the brightmaps from that port as well. They really add to the aesthetics and I would love to see in Woof as well.

If you don't what to add them, that's okay.

**Comment by fabiangreffrath** [comment]
I see two problems with brightmaps:

1. They strictly only work with IWAD assets. Any replacement textures or sprites, even the ones from e.g. Freedoom, may look completely odd and out of place.
2. The choice which pixels to highlight in which textures and sprites is completely subjective and based on (my and @JNechaevsky's) personal taste. There is no canonical implementation that we could rely on. Honestly, I am surprised how few complaints have reached us concerning Crispy's implementation (or Russian Doom's, respectively).

**Comment by rfomin** [comment]
> 2\. Honestly, I am surprised how few complaints have reached us concerning Crispy's implementation (or Russian Doom's, respectively).

This is because this implementation is very good :+1: I think we can add this to Woof.

**Comment by JNechaevsky** [comment]
Sadly, yes. Despite of bmap implementation in Russian Doom is different: custom `COLORMAP`'s based, instead of one `PLAYPAL` based (this gives much more freedom in pixel highlighting but far less compatible with replaced `COLORMAP` lump), potential problem is absolutely same.

I don't see a simple ways of defining "use bmaps or not in PWAD" either. Non simple way is to check for every bmapped texture for replacement, but this is (a) expensive and (b) still may not work well in case of texture just a little bit modified but still supposed to have bright pixels. Not even sure that defining a new micro-standard will be a reasonable idea.

Perhaps we can ask @bradharding for recommendation, since he have an `NOBRIGHTMAP` flag for `MAPINFO` lump?
https://github.com/bradharding/doomretro/wiki/INFORMATION-FOR-MAPPERS#MAPINFO-LUMPS
