### ISSUE TITLE
Alien Vendetta Map 20 segfaults with Freedoom but not Doom 2

### ISSUE THREAD

**Issue by doomcup** [fabiangreffrath/woof#469]
Playing through Alien Vendetta and reached a part of Map 20 that would crash if I was using Freedoom but not Doom 2. Suspect it's to do with textures because it happens when rounding a corner.

The same area does not segfault when using Chocolate-Doom. 

```
doomcup@bernice:~ $ woof -iwad freedoom2.wad -file AV.WAD AVmidi.wad -deh AV.DEH
Looking in .
Looking in .
Looking in /home/doomcup
Looking in /usr/local/share/woof
Looking in /home/doomcup/.local/share/games/doom
IWAD found: /home/doomcup/.local/share/games/doom/freedoom2.wad
DOOM II version
                         DOOM 2: Hell on Earth v2.03                           
Built on Mar  1 2022
M_LoadDefaults: Load system defaults.
 default file: /home/doomcup/.local/share/woof/woof.cfg
V_Init: allocate screens.
W_Init: Init WADfiles.
 adding /home/doomcup/.local/share/games/doom/freedoom2.wad
 adding /home/doomcup/.local/share/games/doom/AV.WAD
 adding /home/doomcup/.local/share/games/doom/AVmidi.wad

Loading DEH file (WAD)
Loading DEH file /home/doomcup/.local/share/games/doom/AV.DEH
Loading DEH file /usr/local/share/woof/autoload/doom-all/bloodcolor.deh
M_Init: Init miscellaneous info.
R_Init: Init DOOM refresh daemon - [ ...................         ]
R_InitData
R_InitPlanes
R_InitLightTables
R_InitSkyMap
R_InitTranslationsTables

P_Init: Init Playloop state.
I_Init: Setting up machine state.
I_InitJoystick: Failed to open game controller.
I_InitSound: Configured audio device with 2048 samples/slice.
Precaching all sound effects...done.
I_InitMusic: Using SDL_mixer.
OPL_Init: Using driver 'SDL'.
NET_Init: Init network subsystem.
D_CheckNetGame: Checking network game status.
startskill 3  deathmatch: 0  startmap: 1  startepisode: 1
player 1 of 1 (1 nodes)
S_Init: Setting up sound.
S_Init: default sfx volume 10
HU_Init: Setting up heads up display.
ST_Init: Init status bar.
P_SetupLevel: map20 (AV.WAD), Doom nodes
 Skill 1, Total 0:00:00
 Demo Version 109
G_DoLoadGame: Slot 0, MAP20 (AV.WAD), Skill 1, Time 00:12:24/03:33:31
I_SignalHandler: Exit on Segmentation fault (Signal 11)
```

Attached is a save file right before rounding the corner that does it
[woofsav0.dsg.zip](https://github.com/fabiangreffrath/woof/files/8164531/woofsav0.dsg.zip)
.

**Comment by fabiangreffrath** [comment]
Wait a minute! Did you create the savegame with Doom 2 as the IWAD and then try to load it with Freedoom 2 as the IWAD? 

I am asking, because if running with Doom 2 as the IWAD, `firstflat+238` is a lump called "CEIL4_1" which is the well expected cailing flat for the area you are about to enter. The number `238` is the "ceilingpic" of the affected sectors that is saved relative to `firstflat`. But since Doom 2 and Freedoom 2 have a different number of flats, the number `firstflat+238` happens to point to lump "CEIL4_1" with Doom 2 as the IWAD and to lump "F3_END" with Freedoom 2 as the IWAD - and the latter happens to be an empty marker lump which causes the crash in the drawing function.

Please don't expect savegames to keep on working if you exchange the IWAD meanwhile. This is like pulling the carpet under the savegame's feet. 😉

**Comment by fabiangreffrath** [comment]
Just checked, the level runs fine if started with Freedoom 2 as the IWAD.

**Comment by doomcup** [comment]
Ah, gotcha. I did indeed create the save in Doom 2. I had no idea there was such issues. Thanks.

**Comment by fabiangreffrath** [comment]
> Ah, gotcha. I did indeed create the save in Doom 2. I had no idea there was such issues. Thanks.

Never mind. I have added some safety measures to prevent such crashes from happening in the future.
