### ISSUE TITLE
Weapon autoswitch when ammo is depleted

### ISSUE THREAD

**Issue by rfomin** [fabiangreffrath/woof#578]
I've got a bug report: "it seems there's a bug where when BFG or whatever other gun ammo is depleted, it's always switched to SSG despite I was pressing 5 or something. I tried this on other ports and it seems it's fine. It happens on cl21, but I'm not sure about other cl. (I remember PrBoom+ 2.5.1.7um has this bug on cl9 as well, so I guess it's a similar problem)"
I have seen some fixes in PrBoom+/DSDA-Doom about this: https://github.com/coelckers/prboom-plus/commit/be592357a8251b2452d6147f16392d2577877257 and https://github.com/kraflab/dsda-doom/commit/7bb955b801a0eb466cb20f66674d6e33ee7942b2#commitcomment-66533351 and more :smile: 
@fabiangreffrath Is it worth fixing and which approach to choose?

**Comment by NightFright2k19** [comment]
Tested behavior in Doom 1, CL2:
When BFG/Plasma Gun is empty, game switches to chaingun. When that one is empty, shotgun is used. Rocket launcher is skipped entirely, even with full rocket ammo.

**Comment by rfomin** [comment]
> Tested behavior in Doom 1, CL2:
> When BFG/Plasma Gun is empty, game switches to chaingun. When that one is empty, shotgun is used. Rocket launcher is skipped entirely, even with full rocket ammo.

I think this is expected, weapon switching should be compatible with vanilla on complevel 2. This bug is related to the complevel boom and above.

**Comment by fabiangreffrath** [comment]
> I have seen some fixes in PrBoom+/DSDA-Doom about this: ... and ... and more 😄 @fabiangreffrath Is it worth fixing and which approach to choose?

Yes, this has caused some major trouble in PrBoom+ in the past.

First, we applied the fix:
https://github.com/coelckers/prboom-plus/commit/be592357a8251b2452d6147f16392d2577877257

Then, we needed a fix for the fix:
https://github.com/coelckers/prboom-plus/commit/febe0e16b855b9f893be2268e782596edb984509

Then some cosmetic fix for a compiler warning:
https://github.com/coelckers/prboom-plus/commit/8069af91af696ee3fa7e58a8f6a93c7533a767e4

And then another logic fix:
https://github.com/coelckers/prboom-plus/commit/05b81cc9f4e3a9961cccaf762a3fa27d9f767b12

And now DSDA added another fix on top of that...

So, you may guess that I am *really* reluctant to introduce this mess into Woof!, unless there is a compelling and convincing reason to do so and unless we are absolutely sure that the fix we are about to apply doesn't introduce more bugs than it actually fixes. I am not going to go through this again.

> Tested behavior in Doom 1, CL2: When BFG/Plasma Gun is empty, game switches to chaingun. When that one is empty, shotgun is used. Rocket launcher is skipped entirely, even with full rocket ammo.

Do you mean you have tested this with DOOM.exe or with `woof -complevel 2`? Because, in the latter case, the code path in question isn't even triggered. This is about fixing the _Boom_ autoswitch behaviour.

**Comment by kraflab** [comment]
One thing I'll say is that the "fixed" behaviour is quite important to some players, so it might be worth it. The extra stuff in dsda-doom (`dsda_SwitchWhenAmmoRunsOut` option) was also a popular addition. For what it's worth, I'm at least 90% confident there aren't more bugs... 🙂

**Comment by fabiangreffrath** [comment]
Hm, I think I will need a PR for this. Does this require a menu switch or can we just enable this unconditionally?

**Comment by rfomin** [comment]
> Hm, I think I will need a PR for this. Does this require a menu switch or can we just enable this unconditionally?

I think we can enable this unconditionally, it feels like a bug.

**Comment by fabiangreffrath** [comment]
So, in DSDA the `dsda_SwitchWhenAmmoRunsOut` feature has entirely replaced the `boom_autoswitch` switch? So, there is only one menu item left to enable or disable automatic weapon switching - and "enabled" always means the fixed behaviour?

**Comment by kraflab** [comment]
The switch when ammo runs out is a different feature unrelated to the bug fix. By default in boom when you run out of ammo (and even before you try to fire the weapon again), the port automatically inserted a weapon swap to the next best weapon. This may sound sensible, but if you're running around an arena firing rockets for instance, and you run out, you may go to pick up another box and don't want to need to swap weapons again. That's essentially the type of use case.

**Comment by fabiangreffrath** [comment]
Wouldn't part of the problem already be mitigated if we used `P_SwitchWeaponMBF21()` instead of regular `

**Comment by rfomin** [comment]
> Wouldn't part of the problem already be mitigated if we used `P_SwitchWeaponMBF21()` instead of regular `P_SwitchWeapon()`? Shouldn't we just use it unconditionally?

As far as I understand the issue is that you can't "cancel" auto-switch in complevel boom or higher. In complevel vanilla the player has time to press a button to switch to another weapon and "cancel" the auto-switch.
