### ISSUE TITLE
Woof creates an autoload folder in the current directory when called from $PATH.

### ISSUE THREAD

**Issue by 4ffy** [fabiangreffrath/woof#610]
I have Woof compiled and installed on Linux, and it is creating an empty `autoload` folder in whatever the current directory is when the program is called.

I think Woof tries to create its autoload folders in, [among other locations](https://github.com/fabiangreffrath/woof/blob/ec9aa62bab4bb4d4dc3802795f907d3fd063ebb2/src/d_main.c#L669), the directory pointed to by [D_DoomExeDir](https://github.com/fabiangreffrath/woof/blob/ec9aa62bab4bb4d4dc3802795f907d3fd063ebb2/src/d_main.c#L580), which may still return the current directory when Woof is called as simply `woof` from another location via the system `$PATH`, as is customary for Linux programs. Commenting out the D_DoomExeDir autoload declaration and recompiling bypasses the issue.

This also seems to happen if you add Woof to the `%PATH%` on Windows and call it from the command line. It does *not* occur if you call Woof with a full pathname.

**Comment by fabiangreffrath** [comment]
The call to `D_DoomExeDir()` has been added, so that local, i.e. non-installed, builds can find their autoload directory in their respective build directory. I agree, however, that the autoload directory should not get created if it isn't available yet. 

Windows users are expected to double-click the executable icon after unpacking. Supporting Windows on the command line is somehow awkward and will probably not be improved any further.
