### ISSUE TITLE
R_FlatNumForName: - not found When running DBP11.wad

### ISSUE THREAD

**Issue by ice44** [fabiangreffrath/woof#72]
When trying to run Lilywhite Lilith this error occurs. Has never happened before so I have no idea what changed.

Mouse issues are still present as well, there is what feels like mouse acceleration being applied.

The Chaingun has been a bit wonky as well, firing erratically and inconsistently.

Hopefully we can nail these down.

**Comment by fabiangreffrath** [comment]
> When trying to run Lilywhite Lilith this error occurs. Has never happened before so I have no idea what changed.

I have an idea what causes this. Which map was this and about where on the map did it happen?

> Mouse issues are still present as well, there is what feels like mouse acceleration being applied.

this is because there *is* some acceleration applied. In fact, I have applied the exact same mouse settings as are default in Chocolate Doom and everybody was happy so far. You are the only one so far who complains. :stuck_out_tongue_closed_eyes: 

https://github.com/fabiangreffrath/woof/blob/master/Source/i_video.c#L606

If you could tell me which settings you prefer in Chocolate Doom (or Crispy, that is) I will see if I can adjust things a bit.

> The Chaingun has been a bit wonky as well, firing erratically and inconsistently.

Hm, could possibly be subjective due to the sounds interrupting themselves over and over again.

**Comment by ice44** [comment]
It happened when I was adjusting settings in the menu, I'm sure it was a demo that caused it.

My Acceleration both horizontal and vertical is 1.0, My speed for both horizontal and vertical is 32. Having it granular and exact really helps a lot. The default acceleration imo is muddy and inexact. Throws muscle memory out of the window.

I keep the acceleration at 1.0, sometimes I like to tweak the speed a bit, but it has been at 32 for a long while.

**Comment by fabiangreffrath** [comment]
> It happened when I was adjusting settings in the menu, It was the Map08 demo.

Confirmed, I applied a fix for invalid flat names.

> My Acceleration both horizontal and vertical is 1.0, 

I have changed this to your liking in the current code. Should I receive too much negative feedback for this, I 'll have to revert it back, though.
