### ISSUE TITLE
Suggestion: Smoothened Texture Scrolling Toggle

### ISSUE THREAD

**Issue by Some1NamedNate** [fabiangreffrath/woof#729]
I was thinking there'd be a setting that toggles the texture scrolling framerate between 35fps and unlimited.

**Comment by fabiangreffrath** [comment]
Deosn't need a toggle IMHO. If uncapped framerate is enabled, one might expect smooth texture scrolling. The Crispy implementation starts here: https://github.com/fabiangreffrath/crispy-doom/commit/44929d62de508f7b7e08940259f3c1bcd20c5640

**Comment by liPillON** [comment]
speaking of texture scrolling.. I started playing [Saturnine Chapel](https://doomwiki.org/wiki/Saturnine_Chapel) today and I suspect that its signature "green waterfalls" might be broken under woof. 
I'm using the 10.2.0 win64 release and checked it against dsda 0.24.3 (which has a smoother scrolling effect than woof) and gzdoom 4.8.2 (which exhibit the smoothest effect). 
The map requires a boom-compatible engine, so I was especting the same results from all the ports.

**Comment by fabiangreffrath** [comment]
Wow, I just tried this wad with Woof, Crispy Doom and PrBoom+ / DSDA-Doom (with both software and hardware renderer) and these waterfalls look absolutely sickening in all three ports. They resulted in instant head ache, regardless of Vsync and uncapepd framerate. Not sure what to do here, especially since these don't appear to be scrolling textures to me, but animated ones instead... :shrug:

**Comment by fabiangreffrath** [comment]
BTW, it seems these green waterfalls are plain IWAD "SFALL1" textures, so nothing that wouldn't get rendered exactly like this in any other WAD.

**Comment by liPillON** [comment]
oops.. 
sorry for falseflagging this, then..
how the irony of seeing that this hackery results in a pleasant effect only in gzdoom, of all ports..
