### ISSUE TITLE
[Suggestion] Brightmaps adjustment

### ISSUE THREAD

**Issue by NightFright2k19** [fabiangreffrath/woof#740]
Brightmaps for two Doom 1 textures would look better/"cleaner" if certain green tones were excluded from the bm effect: COMP01_1 and COMP1B_4.

Pixels in question have been marked in the attached images.
![COMP01_1](https://user-images.githubusercontent.com/54737241/191182796-dd1bd7d3-b3dd-4d4b-b13c-6119ff83143f.gif) ![COMP1B_4](https://user-images.githubusercontent.com/54737241/191182795-0d2ad052-85e4-4c53-b097-a55b1a695872.gif)

**Comment by fabiangreffrath** [comment]
I guess that's a case for @JNechaevsky! 🚨

**Comment by JNechaevsky** [comment]
Sure, that's my favorite job to do! Both patches are used in `COMPUTE1` texture which was somehow missed on my b-maps testing level. 😳

With little changes and not by adding new exclusive b-map, it will be like this (`COMPUTE2` on left, `COMPUTE1` on right). Missing green color is not very good, but otherwise we'll have some straying pixels:
<details>

![image](https://user-images.githubusercontent.com/21193394/191203116-8afe97ab-0c39-408a-bc22-4e443ea7f5ea.png)

```
static const byte bluegreenbrown[256] =
{
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
};
```

</details>

But this way we'll lost few orange pixels on `COMPUTE2` which is also not good, so it will be better to have unique, nicer one for `COMPUTE2`. 

So the question is: do we want a polished bmap for exactly one texture, or do we want more unified bmap for both textures? It's not about the size of executable, it's mostly about compatibility with custom textures. But since Doom 1 is used less frequently, I believe it will be fine to have a unique one. Anyway, I will need some extra time to make a polished version, will gladly do it in the evening.

**Comment by fabiangreffrath** [comment]
In Woof, we currently have the `COMPUTE1` texture use the `notgrayorbrown` brightmap and the `COMPUTE2` texture use the `bluegreenbrown` brightmap:

```
r_bmaps.c
422:    {"COMPUTE1", DOOM1AND2, notgrayorbrown},
423:    {"COMPUTE2", DOOM1AND2, bluegreenbrown},
```

The `notgrayorbrown` brightmap is used by quite a few other textures, but the `bluegreenbrown` is exclusive to the `COMPUTE2` texture. So, in the end, we already have a 1:1 mapping between brightmap and texture for at least one texture (`COPUTE2`) and I wouldn't mind if we did the same for the `COMPUTE1` texture as well. "Equal rights for all!" 😁

**Comment by fabiangreffrath** [comment]
BTW, I know I have asked this before, but while we are currently talking about brightmaps again: Is there anything in REKKR that could benefit from brightmaps? Has anyone ever taken the effort to check this IWAD for brightmap opportunities?

**Comment by JNechaevsky** [comment]
That's a perfect motivation words, I think it will be named `bluegreenbrownred` as red color will be added. 🙃
Really nice texture, too bad it's pretty rare (or is it appearing only at E2M7 AFAIR?), but fortunatelly we still have custom levels.

> BTW, I know I have asked this before, but while we are currently talking about brightmaps again: Is there anything in REKKR that could benefit from brightmaps? Has anyone ever taken the effort to check this IWAD for brightmap opportunities?

Nope, I haven't. It's a diligently made TC, but I simply not a fan of such TCs and literally finished just E1M1 there.

There was one extra texture from Doom II which fits well from b-mapping, and probably it's currently unique for ID only. Will show as well once I'll get home.

**Comment by fabiangreffrath** [comment]
Cool, I am already looking forward to it!

**Comment by fabiangreffrath** [comment]
I think I like the right variant better. I wouldn't understand why the yellow buttons on the right of the green and blue ribbons are highlighted while the left ones are not.

Regarding `METAL3` I am not sure. Don't you think with the red area highlighted it couldn't get too easily mistaken as a switch?

**Comment by JNechaevsky** [comment]
> I wouldn't understand why the yellow buttons on the right of the green and blue ribbons are highlighted while the left ones are not.

Exactly! That's why keyboards should be either lit or dark on both textures. If you prefer lit keyboard, sure, I'll proceed this way.

> Don't you think with the red area highlighted it couldn't get too easily mistaken as a switch?

Heh, indeed. More of that, I often pressing such texture in custom maps. Not sure why, it's like an... instinct? So yeah, it may be considered as "switch" in some aspects.

**Comment by NightFright2k19** [comment]
I would also go for the version with lit keys, to keep consistency with existing brightmaps and since it simply looks  more interesting.

**Comment by fabiangreffrath** [comment]
https://github.com/fabiangreffrath/woof/commit/147e57c3b6c6bd3287a7885d3866c4faf1fa5900

**Comment by NightFright2k19** [comment]
It's quite alright, that one pixel isn't worth the trouble. Thanks a lot for taking care of the COMPUTE1 brightmaps!
