### ISSUE TITLE
translated keyboard layout for savegames, cheats and chat messages

### ISSUE THREAD

**Issue by fabiangreffrath** [fabiangreffrath/woof#89]
Keyboard input is currently handled by scancode, i.e. independent of the current localization. This means that all key presses are interpreted as if they were hit on a US American keyboard. While this is correct in most places, it may be misleading in others where localized text input is desired, e.g. savegame names, cheats and chat messages.

**Comment by fabiangreffrath** [comment]
@Zodomaniac @JNechaevsky
Friends, I remember we had this discussion before about Vanilla keyboard mapping on or off by default in Crispy Doom (and Chocolate). I am now facing a similar decision for Woof!, where I 'd like to hear the opinion of non-Us-keyboard users about this. 

I mean, in Germany we also use a non-US-keyboard layout, but the only significant difference when typing texts is the switch of the 'Y' and 'Z' keys. But, what do you expect to appear on screen for a game that only supports the Latin alphabet when you hit a key on a keyboard that looks like this (is this what you prefer?):
https://en.wikipedia.org/wiki/JCUKEN#JCUKEN

**Comment by JNechaevsky** [comment]
Evening, @fabiangreffrath!

He-ey, I remember I have touched German keyboard once almost a year ago at job - somebody have purchased a notebook in Germany and brought it to Russia. Having a different placement of `Z` key was totally confusing! In other keys it seems to be same to RU or US layouts.

"JCUKEN" _("ЙЦУКЕН")_ is an established standard for Russian keyboards. There are still some variations of Cyrillic keyboards, like mnemonic, bashkirian, tajik, and others, and some them using non "JCUKEN" layouts... But since "JCUKEN" layout is absolutely same to US "QWERTY" layout, we _(russians)_ does not having any problems.

In more short words: yeah, having an option like in Choco could be helpful for anyone, who is pressing `Y` and in fact, getting pressed `Z` key. It's probably worth an in-game switch, not just hidden variable.

**Comment by fabiangreffrath** [comment]
Sorry everybody, but this is probably not going to change.

While it is true that `keysym.scancode` returns the key's scancode as if pressed on an US-american keyboard and `keysym.sym` maps that key to the current localization, neither of them returns the actual typed character.

This means that on my German keyboard, if I press the 'Y' key, `keysym.scancode` is set to 'Z' and `keysym.sym` is set to 'Y'. So far so good. But what if I want to type an exclamation mark? I'd hit Shift+'1' for that and guess what, both `keysym.scancode` and `keysym.sym` will be set to '1'. So, in order to get shifted characters and certain special symbols, I would have to keep track of the Shift key being held down and provide a translation table from the scancode of the typed key to its shifted value. There is exactly one table of this kind already available in the sources and it is `english_shiftxform[]` in `Source/hu_stuff.c`. I hope it is understandable that I am not going to provide shiftxform tables for each possible keyboard layout.

An alternative approach would be to do what Choco does in `src/i_input.c:GetTypedChar()` and peek for an `SDL_TEXTINPUT` event and extract the fully translated input character from that. However, I don't feel like introducing a hack like this into the code. Especially, because this will probably turn the Key Binding menu into a mess - even more than it is already now,
