### ISSUE TITLE
[Feature request] Change color of automap stats tracker when maximum number is hit

### ISSUE THREAD

**Issue by dististik** [fabiangreffrath/woof#921]
Similar to DSDA-Doom's extended HUD it'd be nice if once the max number of kills (+ archvile resurrects), items, and/or secrets was reached the stat tracker changed colors. This would just make it nicer to do 100% level exits, especially in the case of kills since then you wouldn't need to math out if you got everything including the archvile resurrects.

**Comment by rfomin** [comment]
We have a feature similar to DSDA-Doom's extended HUD, see Options->Setup->Status Bar/HUD->Extended HUD options on 2nd page.

**Comment by dististik** [comment]
The main reason I wanted to request specifically the auto-map tracker is because I'm not a fan of having a visible stat tracker outside of the auto-map. That said, it's very understandably redundant if an extended hud already exists in Woof!.

**Comment by fabiangreffrath** [comment]
With the overhaul of the HUD widgets system, we have also exchanged the explicit three-lines stats tracker with the more compact one-line variant from the Boom HUD. You'll have to enable it in the Setup/Automap menu (an disable the one for the regular view in the Setup/Status Bar/HUD menu, if you like):

![woof0004](https://user-images.githubusercontent.com/6449237/221913504-908b12bf-49f0-4f8e-b0fd-51d4951e0f9b.png)

![woof0011](https://user-images.githubusercontent.com/6449237/221913612-b6181bce-973b-46d6-8b34-5805f8cffe98.png)

If you want it to be printed in the standard Doom HUD font (as the previous three-lines widget was) instead of the Boom HUD font, you'll have to enabled that in the Setup/Status Bar/HUD menu as well:

![woof0009](https://user-images.githubusercontent.com/6449237/221913940-711aeda4-efd2-4cda-8a23-389b0d662eec.png)

The widget will then appear on the Automap like this when reaching 100% kills:

![woof0015](https://user-images.githubusercontent.com/6449237/221914107-0a66d996-f83d-4401-a8b9-f50bb641e9fe.png)

I hope this addresses your request. :wink:

**Comment by fabiangreffrath** [comment]
PS: I'm playing with a custom palette with a lighter blue.

**Comment by dististik** [comment]
That sounds exactly like what I want; are these options in 10.5.1 or just in dev build right now? I can't seem to find them but I also have a habbit of getting lost in menus.

**Comment by fabiangreffrath** [comment]
This is in the dev build only, sorry.

**Comment by dististik** [comment]
No worries! Gives me something to look forward to for a future release then 🙂
