### ISSUE TITLE
[enquiry] fullscreen overlay automap

### ISSUE THREAD

**Issue by liPillON** [fabiangreffrath/woof#936]
minor nitpick/curiosity: 
when using the fullscreen hud, the overlay automap is not drawn over the area usually occupied by the status bar
is this due to drawing routines' constraints or deliberate implementation choice?

would you consider changing this and let the automap span the entire screen area?

![woof0000](https://user-images.githubusercontent.com/48625273/223982604-4a6a1e02-d0f3-4a53-8477-ecba0fa8d1f8.png)

**Comment by fabiangreffrath** [comment]
I am not even sure if this is a bug at all. It just feels "natural" for the Automap to show up above the status bar (or where that is supposed to be). If we ever get to fix this, we must make sure that the Automap does not jump up and down when switching back and forth between the overlay modes.

**Comment by kraflab** [comment]
It covers the whole screen in pr+/dsda-doom. There are lots of games that have a map toggling into overlay mode (more often from a minimap), and they usually use the whole screen in my experience. Since you're changing the position of the map, it makes sense that it does jump when switching modes. Otherwise it would be off center. My 2 cents anyway 🦆

**Comment by fabiangreffrath** [comment]
Oh, cool, thanks for the feedback!
