### ISSUE TITLE
[question] archive formats supported by the "-file" parameter

### ISSUE THREAD

**Issue by liPillON** [fabiangreffrath/woof#955]
I woke up the other day thinking "wouldn't be awesome if Woof was able to load 7zip archives?" 😇 
Eh, sorry for always coming up with these outlandish requests..

Anyway, I performed (under windows) some tests ..
- zip/deflate format, zip extension => wads and lumps are extracted to %TEMP% and loaded in Woof
- zip/deflate format, pk3 extension => no actions
- 7zip/lzma2 format, 7z extension => no actions
- 7zip/lzma2 format, pk7 extension => no actions
- wad file, zip extension => error

..and concluded that:
- Woof supports only the zip/deflate format
- Woof rely on the file having the ".zip" extension to activate this feature

How likely/feasible would supporting other archive formats be?

Thank you again for your work (and patience)

**Comment by rfomin** [comment]
It's easy to add the pk3 format, but I think it can be misleading since it's usually the ZDoom format.

**Comment by fabiangreffrath** [comment]
Support for PK3 files would be easy, in theory, because as you already stated they are merely disguised ZIP files. However, they usually contain their assets in some native format, e.g. PNG, instead of actual lumps.

Support for any other more advanced compression format would mean that we would have to integrate an entire compression library - and in fact we already do in the form of miniz. We needed this for PNG screenshot saving and loading of compressed nodes anyway, so the next logical step was to support extracting WADs and LMPs from ZIP files. However, it is currently restricted to exactly this and, to be honest, I think that's as good as it gets.

This issue reminds me a bit of the requests to integrate a launcher or director browser, which I all rejected so far. In the end, a Doom port is not a file manager. If you have WADs in an archive format more advanced than ZIP, please unpack them before usage. The ZIP format is a notable exception here, because this is how you usually download files from the Doomworld archive.

**Comment by fabiangreffrath** [comment]
as an addendum: libarchive should be the most powerful multi-format archive abstraction library out there. Unfortunately, I wasn't even remotely able to convince them to add a PNG export function [1]. So, if we want this and ZIP support under one hood, I still think we are best off with our miniz solution.

[1] https://github.com/libarchive/libarchive/issues/1900
